require timeout in tests
When running "testrb test/test_rails_autolink.rb", the test suite fails:

  NameError: uninitialized constant TestRailsAutolink::Timeout

Explicitly load the timeout gem during the tests to fix this error.